### ISSUE TITLE
Broken `aqtp-0.1.1` package: missing `aqt` package prefix

### ISSUE THREAD

**Issue by andsteing** [google/aqt#196]
The most recent `aqtp-0.1.1` package is missing the `aqt` prefix in the installed packages:

```
$ pip install aqtp==0.1.1
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting aqtp==0.1.1
  Downloading aqtp-0.1.1-py3-none-any.whl (405 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 405.5/405.5 kB 7.9 MB/s eta 0:00:00
Installing collected packages: aqtp


$ pip show -f aqtp
Successfully installed aqtp-0.1.1
Name: aqtp
Version: 0.1.1
Summary: AQT: Accurate Quantized Training
Home-page: https://github.com/google/aqt
Author: Cerebra Catalyst team
Author-email: cerebra-catalyst-team@google.com
License: 
Location: /usr/local/lib/python3.10/dist-packages
Requires: 
Required-by: 
Files:
  aqtp-0.1.1.dist-info/INSTALLER
  aqtp-0.1.1.dist-info/LICENSE
  aqtp-0.1.1.dist-info/METADATA
  aqtp-0.1.1.dist-info/RECORD
  aqtp-0.1.1.dist-info/REQUESTED
  aqtp-0.1.1.dist-info/WHEEL
  aqtp-0.1.1.dist-info/top_level.txt
  common/__init__.py
  common/__pycache__/__init__.cpython-310.pyc
  common/__pycache__/aqt_common.cpython-310.pyc
  common/__pycache__/aqt_config.cpython-310.pyc
  common/__pycache__/aqt_config_schedule_test.cpython-310.pyc
  common/__pycache__/aqt_config_utils.cpython-310.pyc
  common/__pycache__/emulated_floating_points.cpython-310.pyc
  common/__pycache__/emulation_utils.cpython-310.pyc
  common/aqt_common.py
  common/aqt_config.py
  common/aqt_config_schedule_test.py
  common/aqt_config_utils.py
  common/emulated_floating_points.py
  common/emulation_utils.py
  jax/__init__.py
  jax/__pycache__/__init__.cpython-310.pyc
...
```

Note that these both work as expected:
- `pip install aqtp==0.1.0`
- `pip install aqtp@git+https://github.com/google/aqt.git`

The problem should easily be fixed by

1. yank the faulty 0.1.1 version
2. increase the version to 0.1.2
3. create a new wheel
4. verify the wheel installs correctly (I checked at HEAD and it seems to work as expected; not sure what exactly went wrong when uploading the 0.1.1 package)
5. upload the new version to PyPi

Note that the faulty `0.1.1` package breaks all downstream useres, e.g. https://github.com/google-research/vision_transformer/issues/271

To avoid these problems in the future, it might be a good idea to install an automatic Python publish workflow (e.g. like [this example](https://github.com/google/CommonLoopUtils/blob/main/.github/workflows/python-publish.yml))

**Comment by lukaszlew** [comment]
This is fixed now I believe.
