### ISSUE TITLE
Quantized Batch Normalization?

### ISSUE THREAD

**Issue by sunlex0717** [google/aqt#60]
Hi:

Thanks for your great work and open-sourced quantization codes!
I read your ResNet-4bit and PokeBNN papers and am interested in some GPU acceleration research based on your models.
Here I am a bit confused about the data flow of the model. 

If I understand correctly, your batch normalization operator is not quantized, which means it will operate in bf16 during inference. So in a block with Conv+BN, your Conv layer will output 8/4-bit data, and then it will go through a bf16 BN operator. The output will be bf16 in the end.  Then the bf16 activation data will go to the next Conv layer where it will be first quantized into 8/4-bit data and do quantized Conv operation.

If we consider two blocks with [Conv + BN]. The data will be something like:  bf16->int8/int4 ->(Conv) -> int8/int4 -> bf16 -> (BN) -> bf16->next Block -> bf16.

I am not sure If I understand correctly, Do you have any comments?

Thanks a lot and thanks for your excellent project!

**Comment by lukaszlew** [comment]
Hi, 
Until this point and at least 6 more months we are focusing only on quantization of Tensor ops. 
We have a plan for vector ops, but no coding bandwidth to execute on it right now, sorry.
