### ISSUE TITLE
Publish updated version?

### ISSUE THREAD

**Issue by steve-marmalade** [google/aqt#72]
The current version of this package on pypi is [0.0.9](https://pypi.org/project/aqtp/0.0.9/) doesn't include the fix in #56 , leading to this `ImportError`:

```bash
  File "/opt/conda/lib/python3.7/site-packages/aqt/jax_legacy/jax/compute_cost_utils.py", line 27, in <module>
    from jax.interpreters import masking
ImportError: cannot import name 'masking' from 'jax.interpreters' (/opt/conda/lib/python3.7/site-packages/jax/interpreters/__init__.py)
```

Would you consider releasing a new version?

**Comment by lukaszlew** [comment]
This is done. We will be updating AQT regularly now.
